### ISSUE TITLE
Personal Water Usage: How much is too much?

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/knowledge#11]
@noffle points out that toilets take an amount of water which is an order of magnitude more than the amount used for hydration [Source](https://twitter.com/noffle/status/894031559501664256). For example, five daily flushes is 42 days of drinking water. 

This is an _interesting_ measurement if you are looking at personal water consumption, but it is not a _useful_ metric for curtailing water usage. It is not useful because it lacks context. I could accurately state that [Lake Baikal](https://en.wikipedia.org/wiki/Lake_Baikal) has 5,670 cubic miles of water, or 22% of the surface fresh water on Earth, and therefore it should be drained and Russia should stop hogging water, but it wouldn't make sense to do so. Likewise, stating that 5 gallons of water is a lot of water doesn't say anything about the system in which that variable may be meaningful. 

Tangentially, putting a number on something outside of its context activates internal biases humans have, which result in the impression that large numbers are impressive. You can easily see this by suggesting that I drink 2% of all of the water I actually use, which is small, and therefore I don't need to worry about drinking water, because it's so little. In reality, this could mean I should actually waste less water elsewhere in my life. Framing numbers is important.

A better way of understanding personal water usage is to ask these questions:
- What is the total amount of water in my direct environment?
- How much water is wasted, and how much is recycled?
- What is the cost for the water, and is this cost appropriate given the longevity of the water system?
- What is the source of the water, and is it sustainable?
- How much water do other activities I partake in take? For instance: food, washing, electronics, restaurants, civil services, and so on?
- Is the dollar the most useful metric for the total amount of water used and in the system, and does it reflect my load on the system?
- Is my water subsidized?
- Is personal, consumer curtailment the best way to ensure sustainable water usage?
- Are other activities more relevant: such as eating food which does not take the same amount of irrigation (aka, not almonds)?
- Am I better off dedicating my personal thought-hours elsewhere than my personal consumption: is there a charity, NGO, or co-operative where I can most effectively partition my time to help fight water exploitation? (Phrased another way: am I better off digging an outhouse to stop water consumption, or would I be better off coding a map of water usage that goes viral, promoting knowledgeable water usage?)

The [US](http://www.nbcnews.com/id/21494919/ns/us_news-environment/t/crisis-feared-us-water-supplies-dry/#.WYjgWnVieCg) is experiencing, and will continue to experience, a water shortage that seems to correlate more with human interference than a simple drought can explain. In some areas, the aquifer is being emptied at an unsustainable rate, and there are long term fears about the long term supply of fresh water. 

In other areas, this may be less meaningful. For instance, Montréal appears to have a constant influx of water from the Great Lakes, which it manages at two main water treatment plants in the city. Their website is, unfortunately for my research, in [French](http://ville.montreal.qc.ca/portal/page?_pageid=6497,54201575&_dad=portal&_schema=PORTAL). The main inlet for the Atwater plant can bring in excess of  2,160,000m3 a day [1](https://www.mcgill.ca/waterislife/waterathome/our-drinking-water). 3% of the world's fresh water is in Quebec, most of it in the St. Lawrence [2](http://www.mddelcc.gouv.qc.ca/eau/inter.htm).  Treating this water to make it safe to drink is costly. I don't know how this cost is apportioned, or whether my water bill covers all of it. 

In California, things are obviously more dire. California depends on the snow-pack [1](http://news.nationalgeographic.com/2015/04/150406-california-drought-snowpack-map-water-science/), and drills into the aquifer when it is too small. Unfortunately, the aquifer is a finite resource. The Central Valley used to be almost entirely marshland - now, most of it is farms, which take up most of the water. 

Ideally, water usage is kept minimal, both personally and by businesses, farming, and other large scale uses. However, it is hard to correctly advise exactly how much water ought to be used, and to appropriately apply a price-tag to water usage. Most water humans use needs to be filtered, pumped, and otherwise shipped around in various states: this is expensive. But the tag doesn't reflect the sustainability of the system, but rather current demand and expected short-term trends. This can conflict with advice to consumers - don't flush unless necessary, don't keep the tap on while brushing your teeth, etc - which, in general, suggests cultural microchanges which may be ineffectual overall compared to curtailing business usage and eating sustainable foods. 

It is very hard to go beyond this summary, due to conflicting measurements of water, and difficulty finding relevant details regarding how much water is available in the system. However, in order to have a reasoned discussion about water usage, we may need to do so.

**Comment by noffle** [comment]
Hey Richard. I'm grateful that your questions have led me to do more research on the subject, and improve my understanding of the global water situation. It's been really helpful for clarifying my opinions about water use awareness and conservation.

When I get into dialogues like these with people, I try to check in with myself about *intent*: why am I having this conversation? Is this something I believe in? Am I in the grip of self-righteousness and the desire to be "right"? Has something the other person said triggered something for me, and so, am I *really* actually arguing about that?

I wrote on Twitter about water conversation because I have serious concerns about the rate at which we use water, as a society. [This article about a report](https://www.sciencedaily.com/releases/2014/07/140729093112.htm) says that we will be facing severe water shortages in the next 20 years if our usage habits do not change. It says that electricity production is among the highest users of freshwater, and that many companies don't even track their water use.

I think this stems from a systemic unawareness around water consumption. People don't think about the water they use: it's used as if there are no consequences. It gets me thinking about myself, and how I wasn't even truly aware of my water use. Can I expand my awareness? So I've been measuring my use in my daily life, and I didn't like what I saw. My intention is around a desire to both

a. encourage myself others to examine their own water use, and their society's water use
b. reduce excess water use where they are able

The "where they are able" part is important to me: I think there can be a guilt or anger response sometimes when telling someone without much awareness to change their behaviours. Nobody *should* approach water conservation in a particular way -- it's going to be each individual's personal process.

It seems true from my research that electricity companies and agriculture use the most freshwater, but even if personal water conservation isn't as effective, does that mean we shouldn't bother? I think increasing water use awareness and building conservation habits have positive rippling effects:

1. I'm more likely to be able to handle a drought or emergency situation well, where water resources are scarce
2. I'm more likely to take part in things like petitions or voting for state- or nation-wide water reduction efforts on the scale of electricity/agriculture
3. I'm more likely to talk to friends and family and internet folks about water use awareness and conservation, which can cause a ripple effect across social circles

I think this captures what's important to me, and why I wrote about it on Twitter. I'm grateful that this gave me the opportunity to dig into my intentions more deeply -- thank you for that. :heart:

**Comment by RichardLitt** [comment]
Thanks for writing such a well-meaning, well-crafted, and well thought out message. (Well is a good pun, when talking about water.) 

When I have discussions of this sort, I like to get to the bottom of what I do and what I do not know. Arguing when you do not know something is a very easy way to both make a fool of yourself, and to lead to poor consequences for everyone involved. 

I do not know if Montréal is facing a water shortage, or New England in general (I do know New York may have issues, being New York). As a regionalist, I like to think in terms of locality (ironic, given that I am also, paradoxically, a nomad). Is there a shortage of water in Montréal? It is not likely. May there be a shortage of potable water? Yes. That is why we have the large water treatment plants. Should I be doing more to conserve water to help those out? It is likely, but I doubt it. I just paid my water bill for two months. It was $68 USD. That's little. I think the price would be higher if there was reason to be concerned, and I don't think the water is subsidized (but I do not know). 

I do know that measuring drinking water is inconsequential compared to the amount of water dragged out of California by, say, Nestlé, or the almond industry. (Should I cut back on almonds? Almost certainly). I also know that using large numbers - even if they do not quantify large things - is a cheap way to win an argument. Let me be clear: This was the main point of my original response to you. By appealing to my bias for large numbers being meaningful, I was triggered to say that you were attempting to make the weaker argument the stronger (probably a bad thing, Socrates aside). 

I do understand that personal water awareness is a good thing to have in society, especially in cases like California where it may matter more. I am also curious about other things I don't think about - for instance, and this is a random example, how my living has affected coal mines in West Virginia. Water usage may be high on that list.

**Comment by RichardLitt** [comment]
This is an interesting conversation, but I don't personally worry about my water consumption at the moment. I am going to close this and come back to it if it enters my consciousness again.
